# Generated by Django 4.2.1 on 2023-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerformanceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("packet_loss", models.FloatField()),
                ("latency", models.FloatField()),
                ("bandwidth_utilization", models.FloatField()),
                ("download_speed", models.FloatField()),
                ("upload_speed", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Производительность",
                "verbose_name_plural": "Производительность",
            },
        ),
    ]
